name: sales_crm_pipeline
version: 1.0.0
config-version: 2

profile: sales_crm_pipeline

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  sales_crm_pipeline:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    analytics:
      +schema: analytics
      +materialized: table
